# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 133f8f328cc4565934a4cdd5662832a9828d4438a070ec2b63ab48e2d5eca19283cdb0b60554a46dfc7cd459d574511f6780da11bb370fb179ea576a2fcdf324

test:
  secret_key_base: e88908f1c885cd89d8cf9036d11ebb4778d460908f0c6e97c8da34b868a539505f30fb8f1cbde8ca2f033eb221e33d7d844e5bf74fee5c83e2714d1684b39d8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
